const appLanguage:any = {
  ru:{
    topRanked: "Высший рейтинг",
    newIn: "Новинки",
    makeYourOwn: "Создайте обзор",
    explore: "Обзоры",
    moreReviews: "Больше обзоров",
    logout: "выход",
    login: "Войти через Google",
    reviewName: "Название обзора",
    tags: "Тэги",
    images: "Изображения",
    reviewScore: "Оценка ревью",
    changeTitle: "Изменить тему",
    createReview: "Создать обзор",
    totalReviews: "Количество обзоров",
    registrationDate: "Дата регистрации",
    lastLoginDate: "Дата последнего входа",
    admin: "Админ",
    selectAll: "Выделить всех",
    unSelectAll: "Снять выделение",
    user: "Пользователь",
    role: "Роль",
    status: "Статус",
    rating: "Рейтинг",
    block: "Заблокировать",
    unblock: "Разблокировать",
    delete: "Удалить",
    createReviewText: "Создай свой собственный обзор на любой продукт: книга, фильм, игра. Это поможет другим пользователям узнать мнение людей на интересующий их продукт."
  },
  en:{
    topRanked: "Top ranked",
    newIn: "New in",
    makeYourOwn: "Make your own",
    explore: "Explore",
    moreReviews: "More reviews",
    logout: "log out",
    login: "Login with Google",
    popular: "Popular",
    recent: "Recent",
    newReview: "New review",
    reviewName: "Review name",
    tags: "Tags",
    images: "Images",
    reviewScore: "Review score",
    changeTitle: "change title",
    createReview: "Create review",
    profile: "Profile",
    totalReviews: "Total reviews",
    registrationDate: "Registration date",
    lastLoginDate: "Last login date",
    adminPanel: "Admin panel",
    admin: "Admin",
    selectAll: "Select all",
    unSelectAll: "Unselect all",
    user: "User",
    role: "Role",
    status: "Status",
    rating: "Rating",
    block: "Block",
    unblock: "Unblock",
    delete: "Delete",
    createReviewText: "Create your own review of any project: book, film, game. That can help other users to find out other peoples opinion about the products they interested in."
  }
}

export default appLanguage

